---

- name: "create mountpoint"
  file:
    dest: "{{ item.mount_point | default(mount_root) }}{{ item.name | regex_replace('root', '') }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - "{{ os_volumes[inventory_hostname] }}"
  when:  item.state != "unmanaged"
  tags:
    - mount

- name: "make filesystem"
  filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ item.device }}"
    opts: "-L {{ item.name }}"
  with_items:
    - "{{ os_volumes[inventory_hostname] }}"
  when: item.state != "unmanaged"
  tags:
    - mount

- name: "mount volumes"
  mount:
    name: "{{ item.mount_point | default(mount_root) }}{{ item.name | regex_replace('root', '') }}"
    #src: "{{ item.device }}"
    src: "LABEL={{ item.name }}"
    fstype: "{{ item.fs }}"
    opts: noatime
    state: "{{ item.state }}"
  with_items:
    - "{{ os_volumes[inventory_hostname] }}"
  when: item.state != "unmanaged"
  tags:
    - mount

- name: "set ownership"
  file:
    path: "{{ item.mount_point | default(mount_root) }}{{ item.name | regex_replace('root', '') }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ os_volumes[inventory_hostname] }}"
  when: item.state != "unmanaged"
  tags:
    - mount
